dataset:
  n_max_permutation_size: 5
  gamma: 2.0
  batch_size: 128
  num_workers: 2
  prefetch_factor: 2
encoder:
  n_embed: 128
  n_heads: 4
  n_layers: 6
  attn_dropout: 0.0
  resid_dropout: 0.0
  dtype: "float32"
  device: "cpu"
  init_std: 0.02
  mlp_dropout: 0.0
  ln_eps: 1e-5
  n_output_heads: 2
  n_output_embed: 16
  n_output_rows: 8
  n_output_columns: 8
  activation: "gelu"
  linear_size_multiplier: 4
optimizer:
  lr: 2.0e-4
  warmup_steps: 100
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01
vae:
  gamma: 0.5
  kl_loss_weight: 0.01
  kl_warmup_steps: 500
  kl_warmup_start_weight: 0.0
conv_transformer:
  n_heads: 4
inverter_network:
  n_layers: 3
composer_network:
  n_layers: 3
iterations: 10000
eval_interval: 100
experiment_name: "permutations_group_cpu_default"
wandb_enabled: true
log_interval: 20
reconstruction_loss_weight: 1.0
neural_inv_perm_loss_weight: 0.5
neural_comp_perm_loss_weight: 0.5
latent_inv_perm_loss_weight: 0.01
latent_comp_perm_loss_weight: 0.01
use_ema_target: true
ema_tau: 0.005
