dataset:
  n_max_permutation_size: 10
  gamma: 2.0
  batch_size: 32
  num_workers: 2
  prefetch_factor: 2
encoder:
  n_embed: 64
  n_heads: 4
  n_layers: 4
  attn_dropout: 0.0
  resid_dropout: 0.0
  dtype: "float32"
  device: "cpu"
  init_std: 0.02
  mlp_dropout: 0.0
  ln_eps: 1e-5
  n_output_heads: 2
  n_output_embed: 16
  n_output_rows: 8
  n_output_columns: 8
  activation: "gelu"
  linear_size_multiplier: 4
vae:
  gamma: 0.5
  kl_loss_weight: 1.0
conv_transformer:
  n_heads: 4
iterations: 10000
eval_interval: 100
experiment_name: "permutations_group_cpu_default"
wandb_enabled: false
log_interval: 1
reconstruction_loss_weight: 1.0
